'use client'

import { useMemo, useState } from 'react'
import { ComposableMap, Geographies, Geography, Marker } from 'react-simple-maps'
import { ageGroups, getTrainer, specialties, sports, trainerMatches, trainers, trainingFormats, cityToPercent, type Trainer } from '../lib/trainers'

const geoUrl = 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json'

function VerifiedBadge() { return <span className="verified-badge"><span aria-hidden="true">✓</span> Verified trainer</span> }
function TrainerCard({ trainer, selected, onSelect }: { trainer: Trainer; selected: boolean; onSelect: () => void }) {
  return <button className={`trainer-card ${selected ? 'is-selected' : ''}`} onClick={onSelect} aria-pressed={selected}>
    <img src={trainer.photo} alt={`${trainer.name} profile`} />
    <div className="trainer-card-body"><div className="trainer-card-heading"><h3>{trainer.name}</h3>{trainer.verified && <VerifiedBadge />}</div><p className="trainer-location">{trainer.location} · {trainer.yearsExperience} years coaching</p><p className="trainer-sports">{trainer.sports.join(' · ')}</p><div className="specialty-list">{trainer.specialties.slice(0, 2).map((specialty) => <span key={specialty}>{specialty}</span>)}</div><span className="card-link">View profile <span aria-hidden="true">↗</span></span></div>
  </button>
}

export default function TrainerNetwork() {
  const [query, setQuery] = useState(''); const [sport, setSport] = useState('All Sports'); const [specialty, setSpecialty] = useState('All specialties'); const [ageGroup, setAgeGroup] = useState('All ages'); const [format, setFormat] = useState('All formats'); const [verifiedOnly, setVerifiedOnly] = useState(false); const [selectedId, setSelectedId] = useState(trainers[0].id)
  const filtered = useMemo(() => trainers.filter((trainer) => trainerMatches(trainer, query, sport, specialty, ageGroup, format, verifiedOnly)), [query, sport, specialty, ageGroup, format, verifiedOnly])
  const selected = getTrainer(selectedId); const selectTrainer = (trainer: Trainer) => setSelectedId(trainer.id)
  return <main className="trainers-page">
    <header className="trainers-nav"><a className="brand" href="/">the<span>PORTAL</span></a><nav aria-label="Main navigation"><a href="/">For athletes</a><a href="#network">Preferred Trainers</a><a className="nav-cta" href="/book-demo">Request demo <span aria-hidden="true">↗</span></a></nav></header>
    <section className="trainers-hero"><div><p className="eyebrow">thePORTAL preferred trainers network</p><h1>Find trusted trainers.<br /><em>Train with confidence.</em></h1><p>Connect with verified coaches and performance specialists who understand what it takes to move an athlete forward.</p></div><div className="network-stat"><strong>{trainers.length}+</strong><span>preferred trainers<br />and growing</span></div></section>
    <section className="network-workspace" id="network"><div className="network-toolbar"><div className="search-wrap"><span aria-hidden="true">⌕</span><label className="sr-only" htmlFor="trainer-search">Search trainers, sports, specialties or locations</label><input id="trainer-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search trainers, sports, specialties or locations" /></div><select aria-label="Sport" value={sport} onChange={(event) => setSport(event.target.value)}>{sports.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Specialty" value={specialty} onChange={(event) => setSpecialty(event.target.value)}>{specialties.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Age group" value={ageGroup} onChange={(event) => setAgeGroup(event.target.value)}>{ageGroups.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Training format" value={format} onChange={(event) => setFormat(event.target.value)}>{trainingFormats.map((item) => <option key={item}>{item}</option>)}</select><label className="verified-toggle"><input type="checkbox" checked={verifiedOnly} onChange={(event) => setVerifiedOnly(event.target.checked)} /> Verified only</label></div>
      <div className="network-layout"><div className="map-panel"><div className="map-header"><div><p className="eyebrow">Explore the network</p><h2>Where athletes get better</h2></div><span>{filtered.length} results</span></div><div className="map-canvas"><ComposableMap projection="geoAlbersUsa" projectionConfig={{ scale: 1000 }} width={800} height={470} style={{ width: '100%', height: '100%' }}><Geographies geography={geoUrl}>{({ geographies }) => geographies.map((geo) => <Geography key={geo.rsmKey} geography={geo} fill="#dbe9e8" stroke="#f4f7f8" strokeWidth={0.7} />)}</Geographies>{filtered.map((trainer) => <Marker key={trainer.id} coordinates={[trainer.longitude, trainer.latitude]} onClick={() => selectTrainer(trainer)} className="map-marker"><circle r={trainer.id === selectedId ? 12 : 8} fill={trainer.verified ? '#11a6a1' : '#173246'} stroke="#f4f7f8" strokeWidth={3} /><circle r={3} fill="#f4f7f8" /></Marker>)}</ComposableMap><div className="map-legend"><span><i className="legend-dot verified" /> Verified</span><span><i className="legend-dot network" /> Network</span></div></div></div><aside className="selected-trainer"><div className="selected-cover" /><img className="selected-photo" src={selected.photo} alt={`${selected.name} profile`} /><div className="selected-copy"><div className="selected-name"><h2>{selected.name}</h2>{selected.verified && <VerifiedBadge />}</div><p className="trainer-location">{selected.location} · {selected.sports.join(' · ')}</p><p className="selected-bio">{selected.bio}</p><div className="selected-facts"><span><strong>{selected.yearsExperience}</strong> years coaching</span><span><strong>{selected.ageGroups.length}</strong> age groups</span></div><p className="eyebrow">Development specialties</p><div className="specialty-list">{selected.specialties.map((item) => <span key={item}>{item}</span>)}</div><p className="selected-philosophy">“{selected.philosophy}”</p><div className="selected-actions"><a className="button button-primary" href={selected.profileUrl}>View full profile <span aria-hidden="true">↗</span></a><a className="button button-outline" href="mailto:trainers@theportalathlete.org?subject=Trainer connection">Connect with trainer</a></div></div></aside></div>
    </section>
    <section className="directory"><div className="directory-heading"><div><p className="eyebrow">The preferred trainers network</p><h2>Find your people.</h2></div><p>Every trainer is selected for their expertise, athlete-first approach, and commitment to development.</p></div><div className="trainer-grid">{filtered.map((trainer) => <TrainerCard key={trainer.id} trainer={trainer} selected={trainer.id === selectedId} onSelect={() => selectTrainer(trainer)} />)}</div>{filtered.length === 0 && <div className="empty-state"><h3>Try a broader search.</h3><p>No trainers match those filters yet.</p></div>}</section>
    <footer className="trainers-footer"><a className="brand" href="/">the<span>PORTAL</span></a><span>Education · Performance · Mentorship · Networking</span><a href="mailto:trainers@theportalathlete.org">Become a preferred trainer ↗</a></footer>
  </main>
}
