export type Trainer = {
  id: string; name: string; photo: string; verified: boolean; sports: string[]; location: string
  latitude: number; longitude: number; yearsExperience: number; playingExperience?: string
  specialties: string[]; ageGroups: string[]; trainingFormats: string[]; bio: string; philosophy: string; profileUrl: string
}

export const sports = ['All Sports', 'Basketball', 'Soccer', 'Football', 'Volleyball', 'Hockey', "Women's Flag Football"]
export const specialties = ['All specialties', 'Technical Development', 'Speed & Agility', 'Strength & Conditioning', 'Position Training', 'Basketball Skills', 'Soccer Development', 'Performance', 'Mental Performance', 'Recruiting Preparation', 'Leadership', "Women's Flag Football"]
export const ageGroups = ['All ages', 'Youth', 'Middle school', 'High school', 'College', 'Pro']
export const trainingFormats = ['All formats', 'In-person', 'Small group', 'Virtual', 'Camps']
export const locations = ['All locations', 'Los Angeles, CA', 'San Diego, CA', 'San Francisco, CA', 'New York, NY', 'Miami, FL', 'Dallas, TX', 'Houston, TX', 'Atlanta, GA', 'Chicago, IL', 'Phoenix, AZ', 'Las Vegas, NV', 'Seattle, WA', 'Denver, CO', 'Boston, MA', 'Nashville, TN', 'Charlotte, NC', 'Washington, DC']

const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=320&q=85`
export const trainers: Trainer[] = [
  {id:'maya-williams',name:'Maya Williams',photo:photo('photo-1544005313-94ddf0286df2'),verified:true,sports:['Basketball'],location:'Los Angeles, CA',latitude:34.05,longitude:-118.24,yearsExperience:12,playingExperience:'WNBA development program',specialties:['Basketball Skills','Technical Development','Mental Performance'],ageGroups:['High school','College','Pro'],trainingFormats:['In-person','Small group','Camps'],bio:'Guard development built around confidence, reads, and repeatable habits.',philosophy:'Make the game feel slower by making the work more intentional.',profileUrl:'/trainers/maya-williams'},
  {id:'omar-bennett',name:'Omar Bennett',photo:photo('photo-1500648767791-00dcc994a43e'),verified:false,sports:['Basketball','Football'],location:'Los Angeles, CA',latitude:34.07,longitude:-118.28,yearsExperience:7,playingExperience:'Former collegiate point guard',specialties:['Speed & Agility','Performance','Leadership'],ageGroups:['Youth','Middle school','High school'],trainingFormats:['In-person','Small group'],bio:'Movement training for multi-sport athletes building an explosive base.',philosophy:'Athleticism is a skill you can build every day.',profileUrl:'/trainers/omar-bennett'},
  {id:'kai-morgan',name:'Kai Morgan',photo:photo('photo-1552058544-f2b08422138a'),verified:true,sports:['Soccer'],location:'San Diego, CA',latitude:32.72,longitude:-117.16,yearsExperience:12,playingExperience:'USL Championship',specialties:['Soccer Development','Technical Development','Performance'],ageGroups:['High school','College'],trainingFormats:['In-person','Small group'],bio:'Technical and tactical soccer work for athletes chasing their next level.',philosophy:'Train the player, not just the position.',profileUrl:'/trainers/kai-morgan'},
  {id:'leila-hughes',name:'Leila Hughes',photo:photo('photo-1531123897727-8f129e1688ce'),verified:true,sports:['Volleyball'],location:'San Francisco, CA',latitude:37.77,longitude:-122.42,yearsExperience:9,playingExperience:'Former NCAA outside hitter',specialties:['Technical Development','Position Training','Mental Performance'],ageGroups:['Middle school','High school','College'],trainingFormats:['In-person','Virtual','Camps'],bio:'Complete volleyball development from first contact to college preparation.',philosophy:'Own the details, then trust your game.',profileUrl:'/trainers/leila-hughes'},
  {id:'camila-ortiz',name:'Camila Ortiz',photo:photo('photo-1534528741775-53994a69daeb'),verified:true,sports:['Basketball'],location:'New York, NY',latitude:40.71,longitude:-74.01,yearsExperience:13,playingExperience:'WNBA assistant coach',specialties:['Basketball Skills','Recruiting Preparation','Mental Performance'],ageGroups:['High school','College','Pro'],trainingFormats:['In-person','Virtual','Camps'],bio:'High-level basketball development and recruiting clarity for serious athletes.',philosophy:'The right preparation makes confidence visible.',profileUrl:'/trainers/camila-ortiz'},
  {id:'darius-holt',name:'Darius Holt',photo:photo('photo-1519085360753-af0119f7cbe7'),verified:true,sports:['Football'],location:'New York, NY',latitude:40.76,longitude:-73.98,yearsExperience:11,playingExperience:'Former NFL defensive back',specialties:['Position Training','Speed & Agility','Leadership'],ageGroups:['High school','College','Pro'],trainingFormats:['In-person','Small group','Camps'],bio:'Defensive back training that turns technique into game-day confidence.',philosophy:'Win the rep before the ball arrives.',profileUrl:'/trainers/darius-holt'},
  {id:'sofia-ramirez',name:'Sofia Ramirez',photo:photo('photo-1551836022-d5d88e9218df'),verified:true,sports:['Soccer'],location:'Miami, FL',latitude:25.76,longitude:-80.19,yearsExperience:10,playingExperience:'USL W League',specialties:['Soccer Development','Technical Development','Recruiting Preparation'],ageGroups:['Youth','Middle school','High school'],trainingFormats:['In-person','Camps'],bio:'Technical soccer development that gives young players more ways to solve the game.',philosophy:'Creative players are made through permission, repetition, and play.',profileUrl:'/trainers/sofia-ramirez'},
  {id:'marcus-lee',name:'Marcus Lee',photo:photo('photo-1560250097-0b93528c311a'),verified:true,sports:['Football'],location:'Dallas, TX',latitude:32.78,longitude:-96.8,yearsExperience:15,playingExperience:'Former collegiate safety',specialties:['Speed & Agility','Position Training','Leadership'],ageGroups:['Middle school','High school','College'],trainingFormats:['In-person','Small group'],bio:'Position-specific football training for athletes ready to separate.',philosophy:'Details create distance. We train the details every session.',profileUrl:'/trainers/marcus-lee'},
  {id:'ray-jackson',name:'Ray Jackson',photo:photo('photo-1506794778202-cad84cf45f1d'),verified:false,sports:['Football'],location:'Houston, TX',latitude:29.76,longitude:-95.37,yearsExperience:10,playingExperience:'Former collegiate linebacker',specialties:['Strength & Conditioning','Performance','Position Training'],ageGroups:['Middle school','High school','College'],trainingFormats:['In-person','Small group'],bio:'Build the strength, speed, and habits that travel to game day.',philosophy:'Consistency is the competitive advantage.',profileUrl:'/trainers/ray-jackson'},
  {id:'jordan-brooks',name:'Jordan Brooks',photo:photo('photo-1517841905240-472988babdf9'),verified:false,sports:["Women's Flag Football",'Football'],location:'Atlanta, GA',latitude:33.75,longitude:-84.39,yearsExperience:8,playingExperience:'Former collegiate quarterback',specialties:['Position Training','Leadership','Recruiting Preparation'],ageGroups:['Youth','Middle school','High school'],trainingFormats:['In-person','Camps'],bio:'Quarterback and flag football development centered on decision-making.',philosophy:'Lead with clarity, play with freedom.',profileUrl:'/trainers/jordan-brooks'},
  {id:'devon-price',name:'Devon Price',photo:photo('photo-1524504388940-b1c1722653e1'),verified:true,sports:['Basketball','Volleyball'],location:'Chicago, IL',latitude:41.88,longitude:-87.63,yearsExperience:9,playingExperience:'NCAA Division I athlete',specialties:['Strength & Conditioning','Performance','Speed & Agility'],ageGroups:['High school','College','Pro'],trainingFormats:['In-person','Virtual','Small group'],bio:'Performance coaching for athletes who want to move better and compete longer.',philosophy:'Build a body that lets your skill show up on demand.',profileUrl:'/trainers/devon-price'},
  {id:'nina-petrov',name:'Nina Petrov',photo:photo('photo-1580489944761-15a19d654956'),verified:true,sports:['Hockey'],location:'Boston, MA',latitude:42.36,longitude:-71.06,yearsExperience:14,playingExperience:'NCAA Division I hockey',specialties:['Technical Development','Strength & Conditioning','Leadership'],ageGroups:['Youth','High school','College'],trainingFormats:['In-person','Small group','Camps'],bio:'Skating, edgework, and game IQ for hockey players at every stage.',philosophy:'Effort is a skill. We make it part of the plan.',profileUrl:'/trainers/nina-petrov'},
  {id:'aiden-chen',name:'Aiden Chen',photo:photo('photo-1507003211169-0a1dd7228f2d'),verified:true,sports:['Volleyball'],location:'Seattle, WA',latitude:47.61,longitude:-122.33,yearsExperience:11,playingExperience:'Professional indoor volleyball',specialties:['Technical Development','Speed & Agility','Mental Performance'],ageGroups:['Middle school','High school','College'],trainingFormats:['In-person','Virtual'],bio:'Volleyball skill development for athletes building an elite foundation.',philosophy:'Your best reps are the ones you can repeat under pressure.',profileUrl:'/trainers/aiden-chen'},
  {id:'eli-thompson',name:'Eli Thompson',photo:photo('photo-1501196354995-cbb51c65aaea'),verified:false,sports:['Soccer'],location:'Denver, CO',latitude:39.74,longitude:-104.99,yearsExperience:7,playingExperience:'MLS Next coach',specialties:['Soccer Development','Speed & Agility'],ageGroups:['Youth','Middle school','High school'],trainingFormats:['In-person','Small group'],bio:'Modern soccer training for players who want to own their next action.',philosophy:'Awareness first. Speed follows.',profileUrl:'/trainers/eli-thompson'},
  {id:'ryan-cole',name:'Ryan Cole',photo:photo('photo-1507591064344-4c6ce005b128'),verified:true,sports:['Football'],location:'Phoenix, AZ',latitude:33.45,longitude:-112.07,yearsExperience:10,playingExperience:'Former Pac-12 receiver',specialties:['Speed & Agility','Position Training','Performance'],ageGroups:['Middle school','High school','College'],trainingFormats:['In-person','Camps'],bio:'Receiver and speed development for athletes built to create separation.',philosophy:'Fast is useful. Efficient is unstoppable.',profileUrl:'/trainers/ryan-cole'},
  {id:'sasha-king',name:'Sasha King',photo:photo('photo-1488426862026-3ee34a7d66df'),verified:true,sports:["Women's Flag Football"],location:'Las Vegas, NV',latitude:36.17,longitude:-115.14,yearsExperience:6,playingExperience:'USA Flag Football national team',specialties:["Women's Flag Football",'Position Training','Leadership'],ageGroups:['Youth','Middle school','High school','College'],trainingFormats:['In-person','Camps','Virtual'],bio:'A modern flag football program for athletes ready to compete with confidence.',philosophy:'Your voice belongs on the field.',profileUrl:'/trainers/sasha-king'},
  {id:'taylor-reed',name:'Taylor Reed',photo:photo('photo-1544725176-7c40e5a71c5e'),verified:true,sports:["Women's Flag Football"],location:'Charlotte, NC',latitude:35.23,longitude:-80.84,yearsExperience:8,playingExperience:'National flag football coach',specialties:["Women's Flag Football",'Leadership','Recruiting Preparation'],ageGroups:['Youth','Middle school','High school','College'],trainingFormats:['In-person','Camps','Virtual'],bio:'Helping the next generation of flag football athletes take up space.',philosophy:'Confidence is trained, not granted.',profileUrl:'/trainers/taylor-reed'},
  {id:'monica-ford',name:'Monica Ford',photo:photo('photo-1494790108377-be9c29b29330'),verified:true,sports:['Soccer'],location:'Nashville, TN',latitude:36.16,longitude:-86.78,yearsExperience:13,playingExperience:'Former NWSL midfielder',specialties:['Soccer Development','Mental Performance','Leadership'],ageGroups:['High school','College','Pro'],trainingFormats:['In-person','Small group','Virtual'],bio:'Midfield development and mentorship for complete, composed competitors.',philosophy:'The best players make the people around them better.',profileUrl:'/trainers/monica-ford'},
  {id:'andre-grant',name:'Andre Grant',photo:photo('photo-1535713875002-d1d0cf377fde'),verified:false,sports:['Basketball'],location:'Washington, DC',latitude:38.91,longitude:-77.04,yearsExperience:8,playingExperience:'Former overseas professional',specialties:['Basketball Skills','Recruiting Preparation','Performance'],ageGroups:['Middle school','High school','College'],trainingFormats:['In-person','Small group','Camps'],bio:'Basketball skill sessions built around real reads and recruiting readiness.',philosophy:'Your game deserves a plan.',profileUrl:'/trainers/andre-grant'},
]

export function trainerMatches(trainer: Trainer, query: string, sport: string, specialty: string, ageGroup: string, format: string, verifiedOnly: boolean, location = 'All locations', radius = 'Any distance') {
  const haystack = [trainer.name, trainer.location, trainer.bio, trainer.playingExperience, ...trainer.sports, ...trainer.specialties].join(' ').toLowerCase()
  const locationMatch = location === 'All locations' || trainer.location === location
  const center = trainers.find((item) => item.location === location)
  const radiusMiles = Number.parseInt(radius, 10)
  const distanceMatch = !center || !Number.isFinite(radiusMiles) || distanceMiles(center, trainer) <= radiusMiles
  return (!query || haystack.includes(query.toLowerCase())) && (sport === 'All Sports' || trainer.sports.includes(sport)) && (specialty === 'All specialties' || trainer.specialties.includes(specialty)) && (ageGroup === 'All ages' || trainer.ageGroups.includes(ageGroup)) && (format === 'All formats' || trainer.trainingFormats.includes(format)) && (!verifiedOnly || trainer.verified) && (radius === 'Any distance' ? locationMatch : distanceMatch)
}

function distanceMiles(a: Trainer, b: Trainer) {
  const radians = (value: number) => value * Math.PI / 180
  const lat = radians(b.latitude - a.latitude); const lng = radians(b.longitude - a.longitude)
  const haversine = Math.sin(lat / 2) ** 2 + Math.cos(radians(a.latitude)) * Math.cos(radians(b.latitude)) * Math.sin(lng / 2) ** 2
  return 3959 * 2 * Math.atan2(Math.sqrt(haversine), Math.sqrt(1 - haversine))
}
export function getTrainer(id: string) { return trainers.find((trainer) => trainer.id === id) ?? trainers[0] }
